### ISSUE TITLE
Server error when installing from APT repository

### ISSUE THREAD

**Issue by stissot** [phusion/passenger#1682]
The APT repository currently returns an error when trying to install any Passenger package on Ubuntu 14.04 Precise.

<pre>> cat /etc/apt/sources.list.d/passenger.list
deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main
sudo apt-get update
sudo apt-get install -y passenger
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  passenger-dev passenger-doc ruby-rack
Suggested packages:
  www-browser
The following NEW packages will be installed:
  passenger passenger-dev passenger-doc ruby-rack
0 upgraded, 4 newly installed, 0 to remove and 60 not upgraded.
Need to get 4,794 kB/4,890 kB of archives.
After this operation, 32.3 MB of additional disk space will be used.
Get:1 https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger amd64 1:5.0.21-1~trusty1 [1,473 kB]
Err https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger amd64 1:5.0.21-1~trusty1
  HttpError500
Err https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger-dev amd64 1:5.0.21-1~trusty1
  HttpError500
Err https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger-doc all 1:5.0.21-1~trusty1
  HttpError500
E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/trusty/main/p/passenger/passenger_5.0.21-1~trusty1_amd64.deb  HttpError500

E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/trusty/main/p/passenger/passenger-dev_5.0.21-1~trusty1_amd64.deb  HttpError500

E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/trusty/main/p/passenger/passenger-doc_5.0.21-1~trusty1_all.deb  HttpError500</pre>

**Comment by OnixGH** [comment]
Thanks @stissot, we're working on it now!

**Comment by FooBarWidget** [comment]
The problem was caused by the fact that Amazon S3 changed their SSL certificate. This triggered a security error on our side. This is fixed now.

**Comment by collimarco** [comment]
On Ubuntu 14.04 I have already installed Passenger. When I run apt-get update && apt-get upgrade I get this fatal error:

Get:1 https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main nginx-extras i386 1:1.8.0-8.5.0.23~trusty1 [737 kB]
Get:2 https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger-dev i386 1:5.0.23-1~trusty1 [2148 kB]
Get:3 https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger i386 1:5.0.23-1~trusty1 [1525 kB]
Err https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main passenger i386 1:5.0.23-1~trusty1
HttpError500
Fetched 2885 kB in 9s (309 kB/s) 
E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/trusty/main/p/passenger/passenger_5.0.23-1~trusty1_i386.deb HttpError500
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

What should I do?

**Comment by collimarco** [comment]
Solved: looks like it was a temporary issue.

**Comment by Ambroos** [comment]
I still get this on Debian Jessie. Is there some cache that needs to be cleared?

**Comment by FooBarWidget** [comment]
@Ambroos There was another SSL certificate verification issue. I've fixed that now and it should work now.

**Comment by Ambroos** [comment]
Yep, works now after another `apt-get update`. Thanks!

**Comment by hpoydar** [comment]
Hrm - what am I missing?

    $ cat /etc/apt/sources.list.d/passenger.list
    deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main
    $ sudo apt-get update -y
    $ sudo apt-get install -y nginx-extras passenger
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package passenger

**Comment by OnixGH** [comment]
First step from the [install doc](https://www.phusionpassenger.com/library/install/standalone/install/oss/jessie/) maybe?

**Comment by MiloszFilimowski** [comment]
@hpoydar Did you solve it? I'm following the install doc and have the same problem.

**Comment by CamJN** [comment]
@MiloszFilimowski did you add the key from the keyserver?

**Comment by kaze** [comment]
Sorry guys if it turns out as irrelevant, but if your server's date is not correct, then this behavior happens using apt. Try checking the date, too.

**Comment by MiloszFilimowski** [comment]
@CamJN yes, I did. 
`$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7`
@kaze Unfortunately not the case.

**Comment by CamJN** [comment]
In that case perhaps `sudo apt-get clean; sudo apt-get update` will help.

Which version of ubuntu are you on?

**Comment by MiloszFilimowski** [comment]
I'm on Debian Jessie.

**Comment by CamJN** [comment]
Ok, clearly some step experienced an error, can you run all of the following commands and put the output in a gist?

```
sudo apt-key list
sudo apt-get clean
sudo apt-get update
sudo dpkg -l apt-transport-https ca-certificates
apt show passenger
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
cat /etc/apt/sources.list
```
